"""initial.

Revision ID: a2319e5be78b
Revises:
Create Date: 2025-10-23 14:56:50.670920
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2319e5be78b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'project',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('tg_group_id', sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('project_pkey')),
        sa.UniqueConstraint('name', name=op.f('project_name_key')),
        sa.UniqueConstraint('tg_group_id', name=op.f('project_tg_group_id_key')),
    )
    op.create_index(op.f('project_id_idx'), 'project', ['id'], unique=False)
    op.create_table(
        'user',
        sa.Column('tg_id', sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column('role', sa.Enum('ADMIN', 'ANNOTATOR', 'VALIDATOR', name='user_role'), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('cvat_login', sa.String(length=64), nullable=True),
        sa.Column('tg_username', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('tg_id', name=op.f('user_pkey')),
        sa.UniqueConstraint('cvat_login', name=op.f('user_cvat_login_key')),
    )
    op.create_table(
        'batch',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('batch_project_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('batch_pkey')),
        sa.UniqueConstraint('name', name=op.f('batch_name_key')),
    )
    op.create_index(op.f('batch_project_id_idx'), 'batch', ['project_id'], unique=False)
    op.create_table(
        'user_project',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('user_project_project_id_fkey'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.tg_id'], name=op.f('user_project_user_id_fkey'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'project_id', name=op.f('user_project_pkey')),
    )
    op.create_table(
        'study',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('study_iuid', sa.String(length=255), nullable=False),
        sa.Column('batch_id', sa.Integer(), nullable=False),
        sa.Column('study_path', sa.String(), nullable=False),
        sa.Column('status', sa.Enum('ASSIGNED', 'NEW', 'IN_REVIEW', 'REWORK', 'APPROVED', 'PENDING_CONFIRMATION', 'CLOSED_N', 'CLOSED_I', 'CLOSED_OP', 'CLOSED_F', name='study_status'), nullable=False),
        sa.Column('iteration_count', sa.SmallInteger(), nullable=False),
        sa.Column('annotator_id', sa.BigInteger(), nullable=True),
        sa.Column('expert_id', sa.BigInteger(), nullable=True),
        sa.Column('nc_share_link', sa.String(), nullable=True),
        sa.Column('nc_upload_link', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['annotator_id'], ['user.tg_id'], name=op.f('study_annotator_id_fkey')),
        sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], name=op.f('study_batch_id_fkey'), ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['expert_id'], ['user.tg_id'], name=op.f('study_expert_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('study_pkey')),
    )
    op.create_index(op.f('study_annotator_id_idx'), 'study', ['annotator_id'], unique=False)
    op.create_index(op.f('study_batch_id_idx'), 'study', ['batch_id'], unique=False)
    op.create_index(op.f('study_expert_id_idx'), 'study', ['expert_id'], unique=False)
    op.create_index(op.f('study_status_idx'), 'study', ['status'], unique=False)
    op.create_index(op.f('study_study_iuid_idx'), 'study', ['study_iuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('study_study_iuid_idx'), table_name='study')
    op.drop_index(op.f('study_status_idx'), table_name='study')
    op.drop_index(op.f('study_expert_id_idx'), table_name='study')
    op.drop_index(op.f('study_batch_id_idx'), table_name='study')
    op.drop_index(op.f('study_annotator_id_idx'), table_name='study')
    op.drop_table('study')
    op.drop_table('user_project')
    op.drop_index(op.f('batch_project_id_idx'), table_name='batch')
    op.drop_table('batch')
    op.drop_table('user')
    op.drop_index(op.f('project_id_idx'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
