"""Study status history.

Revision ID: bafbb438aec2
Revises: 27d2c1e6565d
Create Date: 2025-11-10 11:30:56.850376
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as psql


# revision identifiers, used by Alembic.
revision: str = 'bafbb438aec2'
down_revision: Union[str, Sequence[str], None] = '27d2c1e6565d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    study_status_enum = psql.ENUM('ASSIGNED', 'NEW', 'IN_REVIEW', 'REWORK', 'APPROVED', 'APPROVED_F', 'PENDING_CONFIRMATION', 'CLOSED_N', 'CLOSED_I', 'CLOSED_OP', 'CLOSED_F', name='study_status', create_type=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'study_status_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('study_id', sa.Integer(), nullable=False),
        sa.Column('from_status', study_status_enum, nullable=True),
        sa.Column('to_status', study_status_enum, nullable=False),
        sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('iteration_count', sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(['study_id'], ['study.id'], name=op.f('study_status_history_study_id_fkey'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('study_status_history_pkey')),
    )
    op.create_index(op.f('study_status_history_study_id_idx'), 'study_status_history', ['study_id'], unique=False)
    op.create_index(op.f('study_status_history_to_status_idx'), 'study_status_history', ['to_status'], unique=False)
    # ### end Alembic commands ###

    # Функция-триггер: логирует смену статуса
    op.execute(
        """
        CREATE OR REPLACE FUNCTION trg_log_study_status()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
          IF NEW.status IS DISTINCT FROM OLD.status THEN
            INSERT INTO study_status_history(
              study_id, from_status, to_status, iteration_count
            )
            VALUES (
              OLD.id,
              OLD.status,
              NEW.status,
              NEW.iteration_count
            );
          END IF;
          RETURN NEW;
        END;
        $$;
        """,
    )

    # Триггер на изменение статуса
    op.execute("DROP TRIGGER IF EXISTS tr_study_status_history ON study;")
    op.execute(
        """
        CREATE TRIGGER tr_study_status_history
        AFTER UPDATE OF status ON study
        FOR EACH ROW
        WHEN (OLD.status IS DISTINCT FROM NEW.status)
        EXECUTE FUNCTION trg_log_study_status();
        """,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS tr_study_status_history ON study;")
    op.execute("DROP FUNCTION IF EXISTS trg_log_study_status();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('study_status_history_to_status_idx'), table_name='study_status_history')
    op.drop_index(op.f('study_status_history_study_id_idx'), table_name='study_status_history')
    op.drop_table('study_status_history')
    # ### end Alembic commands ###
