"""Add reject_comment_msg_id field.

Revision ID: 81ec4aab6421
Revises: 48d1c9db13ec
Create Date: 2025-11-07 13:42:58.476403
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ec4aab6421'
down_revision: Union[str, Sequence[str], None] = '48d1c9db13ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('reject_comment_msg_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'reject_comment_msg_id')
    # ### end Alembic commands ###
