"""New statuses.

Revision ID: 996bb302aa60
Revises: bafbb438aec2
Create Date: 2025-11-10 17:14:38.132841
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '996bb302aa60'
down_revision: Union[str, Sequence[str], None] = 'bafbb438aec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE study_status ADD VALUE IF NOT EXISTS 'WAITING_REVIEW'")
    op.execute("ALTER TYPE study_status ADD VALUE IF NOT EXISTS 'WAITING_REWORK'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
