"""Add nc_last_upload_link.

Revision ID: 6bdb9b0b26e6
Revises: a2319e5be78b
Create Date: 2025-11-06 11:25:07.456019
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bdb9b0b26e6'
down_revision: Union[str, Sequence[str], None] = 'a2319e5be78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('nc_last_upload_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'nc_last_upload_link')
    # ### end Alembic commands ###
