"""Study category.

Revision ID: 1a8a8c8672f0
Revises: 996bb302aa60
Create Date: 2025-11-11 17:17:46.797575
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8a8c8672f0'
down_revision: Union[str, Sequence[str], None] = '996bb302aa60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'study_category',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('study_category_pkey')),
        sa.UniqueConstraint('name', name=op.f('study_category_name_key')),
    )
    op.create_table(
        'study_category_batch',
        sa.Column('study_category_id', sa.Integer(), nullable=False),
        sa.Column('batch_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], name=op.f('study_category_batch_batch_id_fkey'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['study_category_id'], ['study_category.id'], name=op.f('study_category_batch_study_category_id_fkey'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('study_category_id', 'batch_id', name=op.f('study_category_batch_pkey')),
    )
    op.create_table(
        'study_category_study',
        sa.Column('study_category_id', sa.Integer(), nullable=False),
        sa.Column('study_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['study_category_id'], ['study_category.id'], name=op.f('study_category_study_study_category_id_fkey'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['study_id'], ['study.id'], name=op.f('study_category_study_study_id_fkey'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('study_category_id', 'study_id', name=op.f('study_category_study_pkey')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_category_study')
    op.drop_table('study_category_batch')
    op.drop_table('study_category')
    # ### end Alembic commands ###
