"""Add product field.

Revision ID: 27d2c1e6565d
Revises: 81ec4aab6421
Create Date: 2025-11-07 17:06:47.792307
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d2c1e6565d'
down_revision: Union[str, Sequence[str], None] = '81ec4aab6421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE product_name AS ENUM ('CHEST_CT','HEAD_CT','DX','MMG','DENTAL','SKIN')")
    op.add_column('project', sa.Column('product', sa.Enum(name='product_name'), nullable=True))
    op.execute("UPDATE project SET product = 'CHEST_CT' WHERE product IS NULL")
    op.alter_column('project', 'product', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'product')
    op.execute("DROP TYPE product_name")
    # ### end Alembic commands ###
